import { RecordType } from "./types";

export const records: RecordType[] = [
  {
    id: 1,
    createdAt: new Date().toISOString(),
    lastName: "Doe",
    firstName: "John",
    middleName: "Aaa",
    contactNumber: "09123456789",
    applicationType: "registration",
    gender: "male",
    applicationNumber: "1234567890",
    sk: "15 to 17",
    indigenousPeople: true,
    seniorCitizen: false,
    personWithDisability: false,
  },
  {
    id: 2,
    createdAt: new Date().toISOString(),
    lastName: "Doe",
    firstName: "Jane",
    middleName: "Bbb",
    contactNumber: "09123456789",
    applicationType: "reactivation",
    gender: "female",
    applicationNumber: "1234567891",
    sk: "no",
    indigenousPeople: false,
    seniorCitizen: true,
    personWithDisability: false,
  },
  {
    id: 3,
    createdAt: new Date().toISOString(),
    lastName: "Doe",
    firstName: "Mary",
    middleName: "Ccc",
    contactNumber: "09123456789",
    applicationType: "correction of entries",
    gender: "female",
    applicationNumber: "1234567892",
    sk: "18 to 30",
    indigenousPeople: false,
    seniorCitizen: false,
    personWithDisability: true,
  },
  {
    id: 4,
    createdAt: new Date().toISOString(),
    lastName: "Doe",
    firstName: "Mark",
    middleName: "Ddd",
    contactNumber: "09123456789",
    applicationType: "reactivation with correction",
    gender: "male",
    applicationNumber: "1234567893",
    sk: "no",
    indigenousPeople: true,
    seniorCitizen: true,
    personWithDisability: true,
  },
  {
    id: 5,
    createdAt: new Date().toISOString(),
    lastName: "Doe",
    firstName: "Alice",
    middleName: "Eee",
    contactNumber: "09123456789",
    applicationType: "transfer incoming",
    gender: "female",
    applicationNumber: "1234567894",
    sk: "18 to 30",
    indigenousPeople: false,
    seniorCitizen: false,
    personWithDisability: false,
  },

  {
    id: 6,
    createdAt: new Date().toISOString(),
    lastName: "Nepomuceno",
    firstName: "John Jhigger",
    middleName: "Ventura",
    contactNumber: "09123456789",
    applicationType: "transfer within",
    gender: "male",
    applicationNumber: "1234567895",
    sk: "no",
    indigenousPeople: false,
    seniorCitizen: false,
    personWithDisability: true,
  },
];
